name: Deploy to Azure Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */4 * * *' # Every 4 hours

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      with:
        app-name: "functionapp-${{ env.environment }}"
        slot-name: production
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}